stages:
  - test
  - benchmark
  - lint
  - security
  - deploy

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  RUST_BACKTRACE: "1"

cache:
  paths:
    - .cargo/
    - target/

include:
  - local: '.gitlab/ci/test.yml'
  - local: '.gitlab/ci/benchmark.yml'
  - local: '.gitlab/ci/lint.yml'
  - local: '.gitlab/ci/security.yml'
  - local: '.gitlab/ci/deploy.yml'
