# Rustfmt configuration for fastalloc

# Edition
edition = "2021"

# Maximum line width
max_width = 100

# Hard tabs or spaces
hard_tabs = false
tab_spaces = 4

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

# Formatting options
fn_single_line = false
where_single_line = false
force_explicit_abi = true
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = true
comment_width = 80

# Control flow
control_brace_style = "AlwaysSameLine"
indent_style = "Block"

# Match formatting
match_block_trailing_comma = false
overflow_delimited_expr = true

# Misc
use_small_heuristics = "Default"
use_field_init_shorthand = true
force_multiline_blocks = false
newline_style = "Unix"
