# Rustfmt configuration for fastalloc

# Edition
edition = "2021"

# ============================================================================
# STABLE OPTIONS (work with stable Rust)
# ============================================================================

# Maximum line width
max_width = 100

# Hard tabs or spaces
hard_tabs = false
tab_spaces = 4

# Imports
reorder_imports = true

# Formatting options
force_explicit_abi = true

# Match formatting
match_block_trailing_comma = false

# Misc
use_small_heuristics = "Default"
use_field_init_shorthand = true
newline_style = "Unix"

# ============================================================================
# NIGHTLY-ONLY OPTIONS (uncomment when using nightly rustfmt)
# These options require running: rustup toolchain install nightly
# Then format with: cargo +nightly fmt
# ============================================================================

# Imports organization
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"

# Function formatting
# fn_single_line = false
# where_single_line = false

# Comment formatting
# format_code_in_doc_comments = true
# normalize_comments = true
# wrap_comments = true
# comment_width = 80

# Control flow style
# control_brace_style = "AlwaysSameLine"
# indent_style = "Block"

# Expression formatting
# overflow_delimited_expr = true
# force_multiline_blocks = false
