# .github/ISSUE_TEMPLATE/bug_report.yml
name: "🐛 Bug Report"
description: "File a bug report"
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report! Please provide as much information as possible to help us understand and reproduce the issue."
  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "Steps to reproduce the behavior."
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "fastalloc Version"
      placeholder: "e.g., 1.0.0"
    validations:
      required: true
  - type: input
    id: rust-version
    attributes:
      label: "Rust Version"
      placeholder: "e.g., 1.70.0 (run `rustc --version`)"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: "Operating System"
      description: "OS and version"
      placeholder: "e.g., Ubuntu 22.04, Windows 11, macOS Ventura"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Logs & Error Messages"
      description: "Please include any relevant logs or error messages."
      render: shell
  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here."
      optional: true