# .github/ISSUE_TEMPLATE/question.yml
name: "❓ Question"
description: "Ask a question or seek help"
title: "[Question] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: "Have a question? We're here to help! Please check the documentation first."
  - type: textarea
    id: question
    attributes:
      label: "Your Question"
      description: "Please be as detailed as possible."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "fastalloc Version"
      placeholder: "e.g., 1.0.0"
    validations:
      required: true
  - type: input
    id: rust-version
    attributes:
      label: "Rust Version"
      placeholder: "e.g., 1.70.0 (run `rustc --version`)"
    validations:
      required: true
  - type: textarea
    id: tried
    attributes:
      label: "What have you tried?"
      description: "Let us know what you've already tried."
      optional: true
  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Add any other context about your question."
      optional: true