
name: Pre-Release Checks

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-version:
    name: Check Version Bump
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      
      - name: Check if version was bumped
        run: |
          git fetch origin ${{ github.base_ref }}
          
          CURRENT_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
          git checkout origin/${{ github.base_ref }}
          BASE_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
          
          echo "Base version: $BASE_VERSION"
          echo "Current version: $CURRENT_VERSION"
          
          if [ "$CURRENT_VERSION" = "$BASE_VERSION" ]; then
            echo "⚠️  Warning: Version not bumped in Cargo.toml"
            echo "Consider bumping the version before merging"
          else
            echo "✅ Version bumped from $BASE_VERSION to $CURRENT_VERSION"
          fi

  check-changelog:
    name: Check Changelog
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for changelog update
        run: |
          if [ -f "CHANGELOG.md" ]; then
            if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -q "CHANGELOG.md"; then
              echo "✅ CHANGELOG.md was updated"
            else
              echo "⚠️  Warning: CHANGELOG.md was not updated"
              echo "Consider adding a changelog entry for your changes"
            fi
          else
            echo "⚠️  CHANGELOG.md not found"
          fi
