# Security scanning jobs

audit:
  stage: security
  image: rust:latest
  before_script:
    - cargo install cargo-audit || true
  script:
    - cargo audit
  allow_failure: true

audit:deny:
  stage: security
  image: rust:latest
  before_script:
    - cargo install cargo-deny || true
  script:
    - cargo deny check advisories
  allow_failure: false

sast:
  stage: security
  image: rust:latest
  script:
    - rustup component add clippy
    - cargo clippy -- -W clippy::all
  allow_failure: true
